/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/
SELECT 
	pr.category_id,
	cu.category_name,
	SUM(oi.total_sale) as total_sale,
	SUM(oi.total_sale)/
					(SELECT SUM(total_sale) FROM order_items) 
					* 100
	as contribution
FROM order_items as oi
JOIN
products as pr
ON pr.product_id = oi.product_id
LEFT JOIN category as cu
ON cu.category_id = pr.category_id
GROUP BY pr.category_id,
	cu.category_name
ORDER BY SUM(oi.total_sale) DESC